Simulation from command line using the simulate bash script is now possible (and streamlined)

diff --git a/Simulation/simulate b/Simulation/simulate
--- a/Simulation/simulate
+++ b/Simulation/simulate
@@ -1,8 +1,10 @@
 ARENA=0
 NUMBOTS=10
-#LENGTH=$3
+LENGTH=10000
 SEED=124
 USE_VISUALIZATION=0
+CHECK_OCCLUSIONS=""
+VERBOSE=false
 
 
 
@@ -27,7 +29,7 @@ case $key in
     shift # past argument
     shift # past value
     ;;
-    -v|--visualization)
+    -g|--gui)
     USE_VISUALIZATION=1
     shift # past argument
     ;;
@@ -36,6 +38,29 @@ case $key in
     shift # past argument
     shift # past value
     ;;
+	-c|--check-occlusions)
+	CHECK_OCCLUSIONS="check_occlusions=\"false\""
+	shift # past argument
+	shift # past value
+	;;
+	-v|--verbose)
+	VERBOSE=true
+	shift # past argument
+	shift # past value
+	;;
+	-h|--help)
+	echo "This is a Zebro search mission simulator."
+	echo "Parameters:"
+	echo "[-a || --arena] *id*: use arena id *id*"
+	echo "[-b || --bots] *number*: use *number* amount of bots"
+	echo "[-d || --duration] *seconds*: run the simulation for a maximum duration of *seconds* seconds"
+	echo "[-g || -gui]: run the simulation with visualisation in the Argos GUI"
+	echo "[-c || --check-occlusions]: restrict communication to line-of-sight only"
+	echo "[-v || --verbose]: Verbose output"
+	echo ""
+	echo "Author: Rob van den Berg. Email: robvandenberg@letsinspire.com"
+	exit
+	;;
     *)    # unknown option
     POSITIONAL+=("$1") # save it in an array for later
     shift # past argument
@@ -46,15 +71,18 @@ set -- "${POSITIONAL[@]}" # restore positional parameters
 
 
 
-
-
-echo "Amount of bots: $NUMBOTS"
 VAR=$NUMBOTS
 ROWSIZE=$(bc <<< "scale=0; sqrt($VAR-1)+1")
-echo "rows and columns: $ROWSIZE"
 #SPREADSIZE=$(bc <<< "scale=3; 1/$ROWSIZE")
 SPREADSIZE=0.2
-echo "Spreadsize is $SPREADSIZE"
+
+if [ $VERBOSE = true ]
+then
+	echo "Amount of bots: $NUMBOTS"
+	echo "rows and columns: $ROWSIZE"
+	echo "Spreadsize is $SPREADSIZE"
+	echo "Seed is $SEED"
+fi
 
 STARTX="1.0"
 STARTY="1.0"
@@ -75,10 +103,31 @@ then
 	TARGETX="3.8"
 	TARGETY="3.8"
 fi
+if [ $ARENA = 2 ]
+then
+	CORRECT_ARENA=2
+	echo "You chose arena number 2."
+	STARTX="2.0"
+	STARTY="2.0"
+	WALLS="<box id=\"wall_north\" size=\"2,0.1,0.5\" movable=\"false\"><body position=\"0,1,0\" orientation=\"0,0,0\" /></box><box id=\"wall_south\" size=\"2,0.1,0.5\" movable=\"false\"><body position=\"0,-1,0\" orientation=\"0,0,0\" /></box><box id=\"wall_east\" size=\"0.1,2,0.5\" movable=\"false\"><body position=\"1,0,0\" orientation=\"0,0,0\" /></box><box id=\"wall_west\" size=\"0.1,2,0.5\" movable=\"false\"><body position=\"-1,0,0\" orientation=\"0,0,0\" /></box><box id=\"wall_north2\" size=\"8,0.1,0.5\" movable=\"false\"><body position=\"0,4,0\" orientation=\"0,0,0\" /></box><box id=\"wall_south2\" size=\"8,0.1,0.5\" movable=\"false\"><body position=\"0,-4,0\" orientation=\"0,0,0\" /></box><box id=\"wall_east2\" size=\"0.1,8,0.5\" movable=\"false\"><body position=\"4,0,0\" orientation=\"0,0,0\" /></box><box id=\"wall_west2\" size=\"0.1,8,0.5\" movable=\"false\"><body position=\"-4,0,0\" orientation=\"0,0,0\" /></box>"
+	TARGETX="3"
+	TARGETY="-3"
+fi
+if [ $ARENA = 3 ]
+then
+	CORRECT_ARENA=3
+	echo "You chose arena number 3."
+	STARTX="2.0"
+	STARTY="2.0"
+	WALLS="<box id=\"wall_north\" size=\"2,0.1,0.5\" movable=\"false\"><body position=\"0,1,0\" orientation=\"0,0,0\" /></box><box id=\"wall_south\" size=\"2,0.1,0.5\" movable=\"false\"><body position=\"0,-1,0\" orientation=\"0,0,0\" /></box><box id=\"wall_east\" size=\"0.1,2,0.5\" movable=\"false\"><body position=\"1,0,0\" orientation=\"0,0,0\" /></box><box id=\"wall_west\" size=\"0.1,2,0.5\" movable=\"false\"><body position=\"-1,0,0\" orientation=\"0,0,0\" /></box><box id=\"wall_north2\" size=\"8,0.1,0.5\" movable=\"false\"><body position=\"0,4,0\" orientation=\"0,0,0\" /></box><box id=\"wall_south2\" size=\"8,0.1,0.5\" movable=\"false\"><body position=\"0,-4,0\" orientation=\"0,0,0\" /></box><box id=\"wall_east2\" size=\"0.1,8,0.5\" movable=\"false\"><body position=\"4,0,0\" orientation=\"0,0,0\" /></box><box id=\"wall_west2\" size=\"0.1,8,0.5\" movable=\"false\"><body position=\"-4,0,0\" orientation=\"0,0,0\" /></box>"
+	TARGETX="-3"
+	TARGETY="-3"
+fi
 if [ $CORRECT_ARENA = 0 ]
 then
 	echo "No valid arena specified. Use -v *arena id* to specify an arena"
-	return
+	echo "Use -h or --help to see all possible parameters"
+	exit
 fi
 
 TARGET="<target x=\"$TARGETX\" y=\"$TARGETY\"/>"
@@ -89,17 +138,17 @@ then
 	VISUALIZATION="<visualization><qt-opengl><user_functions library=\"build/loop_functions/zone_loop_functions/libzone_loop_functions\" label=\"zone_qtuser_functions\" /></qt-opengl></visualization>"
 fi
 
-echo "Start coordinates are ($STARTX,$STARTY)"
+
 
 x=0
 y=0
 BOTS=""
 for i in $(seq 1 $NUMBOTS)
 do
-	echo "Welcome $i times"
+	#echo "Welcome $i times"
 	BOTX=$(bc <<< "scale=2; $STARTX+$x*$SPREADSIZE")
 	BOTY=$(bc <<< "scale=2; $STARTY+$y*$SPREADSIZE")
-	echo "BOTX is $BOTX and BOTY = $BOTY"
+	#echo "BOTX is $BOTX and BOTY = $BOTY"
 	
 	
 	BOT="<foot-bot id=\"fb_$i\"><body position=\"$BOTX,$BOTY,0\" orientation=\"0,0,0\" /><controller config=\"fzc\"/></foot-bot>"
@@ -113,25 +162,69 @@ do
 		y=$(($y+1))
 	fi
 done
-echo $TARGET
-echo $WALLS
-echo $BOTS
-echo $LENGTH
 
-sed "s~\$TARGET~$TARGET~g; s~\$WALLS~$WALLS~g; s~\$BOTS~$BOTS~g; s~\$LENGTH~$LENGTH~g; s~\$VISUALIZATION~$VISUALIZATION~g; s~\$SEED~$SEED~g" argos_file_template.txt > generated.argos
+if [ $VERBOSE = true ]
+then
+	echo "Start coordinates are ($STARTX,$STARTY)."
+	#echo $TARGET
+	#echo $WALLS
+	#echo "Using $NUMBOTS bots."
+	echo "Max simulation duration: $LENGTH seconds."
+fi
+
+sed "s~\$TARGET~$TARGET~g; s~\$WALLS~$WALLS~g; s~\$BOTS~$BOTS~g; s~\$LENGTH~$LENGTH~g; s~\$VISUALIZATION~$VISUALIZATION~g; s~\$SEED~$SEED~g; s~\$CHECK_OCCLUSIONS~$CHECK_OCCLUSIONS~g" argos_file_template.txt > generated.argos
 
 
-output=$(argos3 -c generated.argos)
+#output=$(sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" <<< $output)
+
+
+#echo "Starting Process..."
+#TARGET_ID=""
+coproc simulationprocess (trap 'argos3 -c generated.argos < /dev/null & disown' PIPE EXIT) # since it's in the bg, input won't be useful
+
+if [ $VERBOSE = true ]
+then
+	echo "The coprocess array: ${simulationprocess[@]}"
+	echo "The PID of the coprocess is ${simulationprocess_PID}"
+fi
+pid=${simulationprocess_PID}
+pid=$((pid+1))
+echo "Argos3 simulation started with a process ID of $pid"                                                                          
+
+echo "Running the simulation..."
+
+target_found=false
 while read -r line; do
-    echo "$line"
-	if [[ $line == *"Message type is 4"* ]];
+	#kill $pid
+	#line=$(sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' <<< $line)
+	#echo "$line"
+	if [[ $line == *"Mission accomplished"* ]];
 	then
+		target_found=true
 		#echo "Target was found: $line"
+		kill $pid
+		#break;
+		target_found=true
+		line=$(sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' <<< $line)
+		#echo "$line"
+		#TEST=$(sed -e 's/[^0-9]/ /g' <<< $line)
+		NUMBERS=$(echo "$line" | sed -e 's/[^0-9]/ /g' -e 's/^ *//g' -e 's/ *$//g' | tr -s ' ' | sed 's/ /\n/g')
+		TICKS_PASSED=$(echo $NUMBERS | awk '{print $2}')
+		echo -e "\e[32mThe target was found after $TICKS_PASSED ticks.\e[0m"
+		break
 	fi
-done <<< "$output"
-echo "Simulation ended."
+	if [[ $line == "" ]];
+	then
+		echo "No output."
+		#kill $pid
+	fi
+done <&${simulationprocess[0]} # redirect in from coprocess output
 
+if [ $target_found = false ]
+then
+	echo -e "\e[31mThe time limit of $LENGTH seconds was reached and the target was not found.\e[0m"
+fi
 
 status=$?
 ## take some decision ## 
-[ $status -eq 0 ] && echo "$cmd command was successful" || echo "$cmd failed"
+#[ $status -eq 0 ] && echo "$cmd command was successful" || echo "$cmd failed"
